// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.6.0

//# unitInfo: Provides: Expect_test_config
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) == 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function return$0(x){return x;}
   var IO = [0, return$0];
   function sanitize(s){return s;}
   function run(f){return caml_call1(f, 0);}
   var Expect_test_config = [0, IO, run, sanitize, 15023];
   runtime.caml_register_global(0, Expect_test_config, "Expect_test_config");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJleHBlY3RfdGVzdF9jb25maWcuY21hLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbInJldHVybiQwIiwieCIsInNhbml0aXplIiwicyIsInJ1biIsImYiXSwic291cmNlcyI6WyIvVXNlcnMvdHlsYW5tb3Jhbi8ub3BhbS81LjEuMS9saWIvcHB4X2V4cGVjdC9jb25maWcvZXhwZWN0X3Rlc3RfY29uZmlnLm1sIl0sIm1hcHBpbmdzIjoiOzs7Ozs7OztHOzs7OztZQUdNQSxTQUFPQyxHQUFJLE9BQUpBLEVBQUs7R0FITixhQUdORDtZQUdGRSxTQUFTQyxHQUFJLE9BQUpBLEVBQUs7WUFDZEMsSUFBSUMsR0FBSSxPQUFBLFdBQUpBLE1BQVE7b0NBQVpELEtBREFGOzs7RSIsInNvdXJjZXNDb250ZW50IjpbIm1vZHVsZSBJTyA9IHN0cnVjdFxuICB0eXBlICdhIHQgPSAnYVxuXG4gIGxldCByZXR1cm4geCA9IHhcbmVuZFxuXG5sZXQgc2FuaXRpemUgcyA9IHNcbmxldCBydW4gZiA9IGYgKClcbmxldCB1cG9uX3VucmVsZWFzYWJsZV9pc3N1ZSA9IGBDUlxuIl19
