// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.6.0

//# unitInfo: Provides: Time_now
//# unitInfo: Requires: Base, Base__Int63
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) == 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function caml_call2(f, a0, a1){
    return (f.l >= 0 ? f.l : f.l = f.length) == 2
            ? f(a0, a1)
            : runtime.caml_call_gen(f, [a0, a1]);
   }
   var
    global_data = runtime.caml_get_global_data(),
    Base_Int63 = global_data.Base__Int63,
    Base = global_data.Base,
    cst_clock_gettime_CLOCK_REALTI = "clock_gettime(CLOCK_REALTIME) failed";
   function nanoseconds_since_unix_epoch(param){
    var t = runtime.time_now_nanoseconds_since_unix_epoch_or_zero(0);
    return caml_call2(Base_Int63[17], t, Base_Int63[42])
            ? t
            : caml_call1(Base[244], cst_clock_gettime_CLOCK_REALTI);
   }
   var
    Time_now =
      [0,
       nanoseconds_since_unix_epoch,
       function(_a_){
        return runtime.time_now_nanosecond_counter_for_timing(_a_);
       }];
   runtime.caml_register_global(3, Time_now, "Time_now");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJ0aW1lX25vdy5jbWEuanMiLCJzb3VyY2VSb290IjoiIiwibmFtZXMiOlsibmFub3NlY29uZHNfc2luY2VfdW5peF9lcG9jaCIsInQiXSwic291cmNlcyI6WyIvVXNlcnMvdHlsYW5tb3Jhbi8ub3BhbS81LjEuMS9saWIvdGltZV9ub3cvdGltZV9ub3cubWwiXSwibWFwcGluZ3MiOiI7Ozs7Ozs7OztHOzs7OztHOzs7Ozs7Ozs7O1lBeUNJQTtJQUNNLElBQUpDLElBQUk7SUFDTCxPQUFBLDJCQURDQTtjQUFBQTtjQVR5QjtHQVU2Qjs7OztPQUZ4REQ7O1E7Ozs7RSIsInNvdXJjZXNDb250ZW50IjpbIlslJWltcG9ydCBcImNvbmZpZy5oXCJdXG5cbm9wZW4hIEJhc2VcblxuWyUlaWZkZWYgSlNDX0FSQ0hfU0lYVFlGT1VSXVxuXG5leHRlcm5hbCBuYW5vc2Vjb25kc19zaW5jZV91bml4X2Vwb2NoX29yX3plcm9cbiAgOiAgdW5pdFxuICAtPiBJbnQ2My50XG4gID0gXCJ0aW1lX25vd19uYW5vc2Vjb25kc19zaW5jZV91bml4X2Vwb2NoX29yX3plcm9cIlxuICBbQEBub2FsbG9jXVxuXG5leHRlcm5hbCBuYW5vc2Vjb25kX2NvdW50ZXJfZm9yX3RpbWluZ1xuICA6ICB1bml0XG4gIC0+IEludDYzLnRcbiAgPSBcInRpbWVfbm93X25hbm9zZWNvbmRfY291bnRlcl9mb3JfdGltaW5nXCJcbiAgW0BAbm9hbGxvY11cblxuWyUlZWxzZV1cblxuZXh0ZXJuYWwgbmFub3NlY29uZHNfc2luY2VfdW5peF9lcG9jaF9vcl96ZXJvXG4gIDogIHVuaXRcbiAgLT4gSW50NjMudFxuICA9IFwidGltZV9ub3dfbmFub3NlY29uZHNfc2luY2VfdW5peF9lcG9jaF9vcl96ZXJvXCJcblxuZXh0ZXJuYWwgbmFub3NlY29uZF9jb3VudGVyX2Zvcl90aW1pbmdcbiAgOiAgdW5pdFxuICAtPiBJbnQ2My50XG4gID0gXCJ0aW1lX25vd19uYW5vc2Vjb25kX2NvdW50ZXJfZm9yX3RpbWluZ1wiXG5cblslJWVuZGlmXVxuWyUlaWZkZWYgSlNDX1BPU0lYX1RJTUVSU11cblxubGV0W0Bjb2xkXSBnZXR0aW1lX2ZhaWxlZCAoKSA9IGZhaWx3aXRoIFwiY2xvY2tfZ2V0dGltZShDTE9DS19SRUFMVElNRSkgZmFpbGVkXCJcblxuWyUlZWxzZV1cblxubGV0W0Bjb2xkXSBnZXR0aW1lX2ZhaWxlZCAoKSA9IGZhaWx3aXRoIFwiZ2V0dGltZW9mZGF5IGZhaWxlZFwiXG5cblslJWVuZGlmXVxuXG5sZXQgbmFub3NlY29uZHNfc2luY2VfdW5peF9lcG9jaCAoKSA9XG4gIGxldCB0ID0gbmFub3NlY29uZHNfc2luY2VfdW5peF9lcG9jaF9vcl96ZXJvICgpIGluXG4gIGlmIEludDYzLiggPD4gKSB0IEludDYzLnplcm8gdGhlbiB0IGVsc2UgZ2V0dGltZV9mYWlsZWQgKClcbjs7XG4iXX0=
